name: .NET

env:
  versions: 3.0, 3.1.x, 5.0.x
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK ${{ evn.version }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ evn.version }}

